<ul class="accordion">
                        <li id="aboutUs"><a href="#">About VELUX</a>
                        	<ul class="sub-menu">
                        		<li><a href="about-5star.html"><em>01</em>5-Star Specialist</a></li>
                        		<li><a href="about-install.html"><em>02</em>Installed services</a></li>
                        		<li><a href="about-products.html"><em>03</em>Our Products</a></li>
                        		<li><a href="about-warranty.html"><em>04</em>Our Warranty</a></li>
                        		<li><a href="about-why-velux.html"><em>05</em>Why VELUX?</a></li>
                    		</ul>		
                        </li>
                        <li id="whyAdd"><a href="#">Why add a skylight?</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Why daylight?</a></li>
                        		<li><a href="#"><em>02</em>Fresh air</a></li>
                        		<li><a href="#"><em>03</em>Drama</a></li>
                        		<li><a href="#"><em>04</em>Privacy</a></li>
                        		<li><a href="#"><em>05</em>Gain wall space</a></li>
                        		<li><a href="#"><em>06</em>Skylights are desirable</a></li>
                        		<li><a href="#"><em>07</em>SUN TUNNELS ideal for small spaces</a></li>
                        		<li><a href="#"><em>08</em>Daylight control</a></li>
                    		</ul>
                        </li>
                        <li id="whyReplace"><a href="#">Why replace a skylight?</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Why replace skylights</a></li>
                        		<li><a href="#"><em>02</em>Light control, design statement</a></li>
                        		<li><a href="#"><em>03</em>Installation</a></li>
                    		</ul>
                        </li>
                        <li id="products"><a href="#">Products</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Products for all roofs</a></li>
                        		<li><a href="#"><em>02</em>Slope roofs</a></li>
                        		<li><a href="#"><em>03</em>Flat roofs</a></li>
                        		<li><a href="#"><em>04</em>Engineered flashing</a></li>
                    		</ul>
                        </li>
                        <li id="rooms"><a href="#">Residential Rooms</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Master bathrooms</a></li>
                        		<li><a href="#"><em>02</em>Kitchens</a></li>
                        		<li><a href="#"><em>03</em>Living rooms</a></li>
                        		<li><a href="#"><em>04</em>Bedrooms</a></li>
                        		<li><a href="#"><em>05</em>Interior bathrooms</a></li>
                        		<li><a href="#"><em>06</em>Dark spaces</a></li>
                        		<li><a href="#"><em>07</em>Bonus rooms</a></li>
                    		</ul>
                        </li>
                        <li id="upgrade"><a href="#">Upgrade from plastic to glass</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Why make the change?</a></li>
                        		<li><a href="#"><em>02</em>Add fresh air to your home</a></li>
                        		<li><a href="#"><em>03</em>The best valued skylight</a></li>
                    		</ul>
                        </li>
                        <li id="vss"><a href="#">Solar Powered "Fresh Air" Skylight</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Why do I need fresh air skylights?</a></li>
                        		<li><a href="#"><em>02</em>Fresh air skylights = air flow in your home</a></li>
                        		<li><a href="#"><em>03</em>The Solar Powered "Fresh Air" Skylight</a></li>
                        		<li><a href="#"><em>04</em>Innovation</a></li>
                        		<li><a href="#"><em>05</em>Quick facts</a></li>
                        		<li><a href="#"><em>06</em>The Solar Powered "Fresh Air" Skylight video</a></li>
                    		</ul>
                        </li>
                        <li id="whyBlinds"><a href="#">Why blinds?</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Why add a blind to your skylight?</a></li>
                        		<li><a href="#"><em>02</em>Blinds are about more than just light control</a></li>
                        		<li><a href="#"><em>03</em>Fully integrated products</a></li>
                        		<li><a href="#"><em>04</em>Make a design statement</a></li>
                        		<li><a href="#"><em>05</em>Save money by doing it now</a></li>
                        		<li><a href="#"><em>06</em>Controlling your environment</a></li>
                        		<li><a href="#"><em>07</em>Maximum energy efficiency</a></li>
                        		<li><a href="#"><em>08</em>Daylight control</a></li>
                        		<li><a href="#"><em>09</em>Factory installed</a></li>
                    		</ul>
                        </li>
                        <li id="roofWindows"><a href="#">Roof windows</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Create a room in the roof</a></li>
                        		<li><a href="#"><em>02</em>Roof windows ideal for renovated attic space</a></li>
                        		<li><a href="#"><em>03</em>Why natural light from above?</a></li>
                        		<li><a href="#"><em>04</em>Solutions</a></li>
                        		<li><a href="#"><em>05</em>Photo gallery</a></li>
                    		</ul>
                        </li>
                        <li id="sunTunnel"><a href="#">SUN TUNNEL skylights</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>SUN TUNNEL skylights</a></li>
                        		<li><a href="#"><em>02</em>Options</a></li>
                        		<li><a href="#"><em>03</em>Before & After</a></li>
                        		<li><a href="#"><em>04</em>Installation</a></li>
                    		</ul>
                        </li>
                        <li id="history"><a href="#">History</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>VELUX History</a></li>
                        		<li><a href="#"><em>02</em>Our name</a></li>
                        		<li><a href="#"><em>03</em>Our goal</a></li>
                        		<li><a href="#"><em>04</em>Transform space</a></li>
                        		<li><a href="#"><em>05</em>Products for the entire house</a></li>
                        		<li><a href="#"><em>06</em>Technology leader</a></li>
                        		<li><a href="#"><em>07</em>Daylight control</a></li>
                        		<li><a href="#"><em>08</em>"No Leak" warranty</a></li>
                    		</ul>
                        </li>
                        <li id="installation"><a href="#">Installation</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>Skylight installation</a></li>
                        		<li><a href="#"><em>02</em>SUN TUNNEL installation</a></li>
                    		</ul>
                        </li>
                        <li id="warranty"><a href="#">Warranty information</a>
                        	<ul class="sub-menu">
                        		<li><a href="#"><em>01</em>10 year "No Leak" warranty</a></li>
                        		<li><a href="#"><em>02</em>Deck mounted skylight 3 layers of protection</a></li>
                        		<li><a href="#"><em>02</em>Curb mounted skylight 3 layers of protection</a></li>
                    		</ul>
                        </li>
                        <li id="galleries"><a href="#">Galleries</a>
                            <ul class="sub-menu">
                                <li><a href="apps-galleries/bathroom/index.html"><em>01</em>Bathroom</a></li>
                                <li><a href="apps-galleries/kitchen/index.html"><em>02</em>Kitchen</a></li>
                                <li><a href="apps-galleries/living_room/index.html"><em>03</em>Living room</a></li>
                                <li><a href="apps-galleries/bedroom/index.html"><em>04</em>Bedroom</a></li>
                                <li><a href="apps-galleries/small_spaces/index.html"><em>05</em>Dark spaces</a></li>
                                <li><a href="apps-galleries/bonus/index.html"><em>06</em>Bonus room</a></li>
                                <li><a href="apps-galleries/suntunnel/index.html"><em>07</em>SUN TUNNEL skylights</a></li>
                                <li><a href="apps-galleries/exterior/index.html"><em>08</em>Exterior</a></li>
                            </ul>
                        </li>
                        <li id="galleries"><a href="config.html">Configuration</a></li>
                    </ul>